# Path Related
raw_dataset_dir: 'data/raw/Daftar Saham.xlsx'
raw_dataset_path: data/processed/raw_dataset.pkl
clean_dataset_path: data/processed/clean_dataset.pkl

# Time Series Split Set
train_set_path:
- data/processed/x_train.pkl
- data/processed/y_train.pkl
valid_set_path:
- data/processed/x_valid.pkl
- data/processed/y_valid.pkl
test_set_path:
- data/processed/x_test.pkl
- data/processed/y_test.pkl

# Random Split Set
train_ran_set_path:
- data/processed/x_ran_train.pkl
- data/processed/y_ran_train.pkl
valid_ran_set_path:
- data/processed/x_ran_valid.pkl
- data/processed/y_ran_valid.pkl
test_ran_set_path:
- data/processed/x_ran_test.pkl
- data/processed/y_ran_test.pkl

# Debug Related
print_debug: true

# Columns by data type related
datetime_index: datetime64[ns]
float_columns: dataset.columns[1:]

# Predictors and Target Related
target: BMRI.JK
predictors: All columns except target

# Range of Data Related
range_date:
- 2020-01-01
- Today()

# ticker related data
ticker_ext: .JK
start_date: !!str 2017-01-01
end_date: date.today()
interval_date: 1d

range_other_columns:
- -1.0
- 1.0

# Replacement for missing value related
